### ISSUE TITLE
OTG not working

### ISSUE THREAD

**Issue by peterbmckinley** [aodzip/buildroot-tiny200#11]
Hi we have a partially working image based on the V2 firmware from MangoPi

https://github.com/mangopi-sbc/buildroot-mangopi-r

However OTG doesn't work, lsusb prints no info at all with a usb wifi dongle connected.

We set dr_mode to HOST instead of PERIPHERAL

Is there something else we need to do, in addition to this? Unfortunately the repo above has disabled Issue reporting

**Comment by MangoNoFlake** [comment]
if we use PA1 for OTG-ID, then :
``` sh
&usb_otg {
dr_mode = "otg"; /* host peripheral otg*/
status = "okay";
};
&usbphy {
status = "okay";
usb0_id_det-gpios = <&pio 0 1 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>; /* PA1    0a1b2c3d4e5f6g7h */
};
```
I tested, it works.

**Comment by peterbmckinley** [comment]
Thanks Mangobuge. Can we make this the default and submit a pull request to https://github.com/ouki-wang/buildroot-f1c-pinpong

Peter

**Comment by peterbmckinley** [comment]
> if we use PA1 for OTG-ID, then :
> 
> ```shell
> &usb_otg {
> dr_mode = "otg"; /* host peripheral otg*/
> status = "okay";
> };
> &usbphy {
> status = "okay";
> usb0_id_det-gpios = <&pio 0 1 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP)>; /* PA1    0a1b2c3d4e5f6g7h */
> };
> ```
> 
> I tested, it works.

We copied your dts but it made no difference.

"# lsusb
#"

According to the Schematic, the ID pin is not connected

**Comment by Patchy319** [comment]
@peterbmckinley Greetings, I did some testing with my own F1C200s dev board and found setting it to this, gave me the desired result:
``` sh
&usb_otg {
dr_mode = "host"; /* host peripheral otg*/
status = "okay";
};
&usbphy {
status = "okay";
};
```
I used this to get my USB Ethernet Adapter to work. This may be what you are looking for. Please let me know if this is helpful, it took me a lot of troubleshooting myself! :)

**Comment by peterbmckinley** [comment]
I haven't tested it, my project has moved on, but if it worked for you i'm happy to close the issue on that basis.

Thank for your help!
