### ISSUE TITLE
make target-post-image error

### ISSUE THREAD

**Issue by CharlesHe023** [aodzip/buildroot-tiny200#2]
Number of duplicate files found 3
Number of inodes 713
Number of files 315
Number of fragments 24
Number of symbolic links  342
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 56
Number of ids (unique uids + gids) 2
Number of uids 2
        root (0)
        unknown (33)
Number of gids 2
        root (0)
        unknown (33)
^[[7m>>>   Generating filesystem image rootfs.tar^[[27m
mkdir -p /disk0/Charles/linux/allwinner/buildroot-tiny200/output/images
rm -rf /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar
mkdir -p /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar
rsync -auH --exclude=/THIS_IS_NOT_YOUR_ROOT_FILESYSTEM /disk0/Charles/linux/allwinner/buildroot-tiny200/output/target/ /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/target
echo '#!/bin/sh' > /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/fakeroot
echo "set -e" >> /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/fakeroot
echo "chown -h -R 0:0 /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/target" >> /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/fakeroot
PATH="/disk0/Charles/linux/allwinner/buildroot-tiny200/output/host/bin:/disk0/Charles/linux/allwinner/buildroot-tiny200/output/host/sbin:/opt/rh/devtoolset-7/root/usr/bin:/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/X11R6/bin:/home/Charles/.local/bin/pha-all/arcanist/bin:/home/Charles/.local/depot_tools:/home/Charles/.local/bin:/home/Charles/bin:/home/Charles/.local/bin/pha-all/arcanist/bin:/home/Charles/.local/depot_tools" /disk0/Charles/linux/allwinner/buildroot-tiny200/support/scripts/mkusers /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/full_users_table.txt /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/target >> /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/fakeroot
echo "/disk0/Charles/linux/allwinner/buildroot-tiny200/output/host/bin/makedevs -d /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/full_devices_table.txt /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/target" >> /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/fakeroot
printf '        rm -rf /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/target//etc/udev/hwdb.d/\n' >> /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/fakeroot
printf '   \n' >> /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/fakeroot
printf '        (cd /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/target; find -print0 | LC_ALL=C sort -z | tar  --pax-option=exthdr.name=%%d/PaxHeaders/%%f,atime:=0,ctime:=0 -cf /disk0/Charles/linux/allwinner/buildroot-tiny200/output/images/rootfs.tar --null --xattrs-include='\''*'\'' --no-recursion -T - --numeric-owner)\n' >> /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/fakeroot
chmod a+x /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/fakeroot
PATH="/disk0/Charles/linux/allwinner/buildroot-tiny200/output/host/bin:/disk0/Charles/linux/allwinner/buildroot-tiny200/output/host/sbin:/opt/rh/devtoolset-7/root/usr/bin:/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/X11R6/bin:/home/Charles/.local/bin/pha-all/arcanist/bin:/home/Charles/.local/depot_tools:/home/Charles/.local/bin:/home/Charles/bin:/home/Charles/.local/bin/pha-all/arcanist/bin:/home/Charles/.local/depot_tools" FAKEROOTDONTTRYCHOWN=1 /disk0/Charles/linux/allwinner/buildroot-tiny200/output/host/bin/fakeroot -- /disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/fakeroot
rootdir=/disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/tar/target
table='/disk0/Charles/linux/allwinner/buildroot-tiny200/output/build/buildroot-fs/full_devices_table.txt'
ln -snf /disk0/Charles/linux/allwinner/buildroot-tiny200/output/host/arm-buildroot-linux-gnueabi/sysroot /disk0/Charles/linux/allwinner/buildroot-tiny200/output/staging
^[[7m>>>   Executing post-image script board/allwinner/suniv-f1c100s/scripts/genimage.sh^[[27m
make: *** [target-post-image] Error 1

**Comment by aodzip** [comment]
Are you using some environment like WSL or WSL2

**Comment by CharlesHe023** [comment]
> Are you using some environment like WSL or WSL2

My environment is CentOS 7

**Comment by aodzip** [comment]
I suggest using Ubuntu 18.04/20.04 and use normal ext4 filesystem to build.
