### ISSUE TITLE
support for lcd on lichee nano board

### ISSUE THREAD

**Issue by road24** [aodzip/buildroot-tiny200#3]
I can't see the startup messages on the lcd , I don't even have a framebuffer, is the lcd support broken on this kernel version or maybe I'm doing something wrong ?
I'm setting the config using 
`make sipeed_lichee_nano_defconfig  `

The hw I'm using is:
sipeed's lichee nano board
800x600 lcd 
8 GB tf card

**Comment by aodzip** [comment]
I dont actually have a lichee nano，LCD is working on other F1C based board called “Tiny200”

**Comment by road24** [comment]
thanks for the answer, 
It's working now, i just deleted the repo and cloned it again and changed the panel's compatible attribute once i saw fb-test was working.

Closing the issue since it was an error on my side
